apiVersion: v1
kind: Namespace
metadata:
  name: hello-world-prod
  labels:
    name: hello-world-prod
    environment: production
    # Pod Security Standards
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
