apiVersion: v1
kind: ServiceAccount
metadata:
  name: hello-world-sa
  namespace: hello-world-prod
  labels:
    app: hello-world
automountServiceAccountToken: false

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: hello-world-role
  namespace: hello-world-prod
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: hello-world-rolebinding
  namespace: hello-world-prod
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: hello-world-role
subjects:
- kind: ServiceAccount
  name: hello-world-sa
  namespace: hello-world-prod
